name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Build
        run: ./gradlew buildDexJar

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: build/libs

      - name: Publish release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            *.jar
          automatic_release_tag: "latest"
          prerelease: false