name: Build pull request

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Build
        run: ./gradlew buildDexJar
      - name: ls
        run: ls -l
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: build/libs
